CREATE DATABASE if not EXISTS Proyecto_PI2;
USE Proyecto_PI2;

Drop TABLE if EXISTS Acceso_Internet_Velocidad;
CREATE TABLE IF NOT EXISTS Acceso_Internet_Velocidad(
  id INT AUTO_INCREMENT PRIMARY KEY,
  Provincia VARCHAR(255),
  Partido VARCHAR(255),
  Localidad VARCHAR(255),
  Link_Indec INT,
  Otros FLOAT,
  `0,256 mbps` FLOAT,
  `0,375 mbps` FLOAT,
  `0,5 mbps` FLOAT,
  `0,512 mbps` FLOAT,
  `0,625 mbps` FLOAT,
  `0,75 mbps` FLOAT, 
  `1 mbps` FLOAT, 
  `1,25 mbps` FLOAT,
  `1,5 mbps` FLOAT,
  `2 mbps` FLOAT,
  `2,2 mbps` FLOAT,
  `2,5 mbps`FLOAT,
  `3 mbps`FLOAT,
  `3,3 mbps`FLOAT, 
    `3,5 mbps`FLOAT, 
    `4 mbps`FLOAT, 
    `4,5 mbps`FLOAT,
	`5 mbps`FLOAT, 
    `6 mbps`FLOAT, 
    `6,4 mbps`FLOAT, 
    `7 mbps`FLOAT, 
    `7,5 mbps`FLOAT, 
    `8 mbps`FLOAT,
	`9 mbps`FLOAT, 
    `10 mbps`FLOAT, 
    `11 mbps`FLOAT, 
    `12 mbps`FLOAT, 
    `13 mbps`FLOAT, 
    `14 mbps`FLOAT,
	`15 mbps`FLOAT, 
    `16 mbps`FLOAT, 
    `17 mbps`FLOAT, 
    `18 mbps`FLOAT, 
    `19 mbps`FLOAT, 
    `20 mbps`FLOAT,
	`21 mbps`FLOAT, 
    `22 mbps`FLOAT, 
    `23 mbps`FLOAT, 
    `24 mbps`FLOAT, 
    `25 mbps`FLOAT, 
    `25,1 mbps`FLOAT,
	`25,11 mbps`FLOAT, 
    `25,5 mbps`FLOAT, 
    `26 mbps`FLOAT, 
    `30 mbps`FLOAT, 
    `31 mbps`FLOAT, 
    `32 mbps`FLOAT,
	`34 mbps`FLOAT, 
    `35 mbps`FLOAT, 
    `36 mbps`FLOAT, 
    `38 mbps`FLOAT, 
    `39 mbps`FLOAT, 
    `40 mbps`FLOAT,
	`41 mbps`FLOAT, 
    `45 mbps`FLOAT, 
    `46 mbps`FLOAT, 
    `49 mbps`FLOAT, 
    `50 mbps`FLOAT, 
    `55 mbps`FLOAT,
	`58 mbps`FLOAT, 
    `59 mbps`FLOAT, 
    `60 mbps`FLOAT, 
    `61 mbps`FLOAT, 
    `62 mbps`FLOAT, 
    `64 mbps`FLOAT,
	`65 mbps`FLOAT, 
    `66 mbps`FLOAT, 
    `70 mbps`FLOAT, 
    `75 mbps`FLOAT, 
    `78 mbps`FLOAT, 
    `80 mbps`FLOAT,
	`82 mbps`FLOAT, 
    `83 mbps`FLOAT, 
    `85 mbps`FLOAT, 
    `90 mbps`FLOAT, 
    `92 mbps` FLOAT,
  `95 mbps` FLOAT,
  `100 mbps` FLOAT
);

Drop TABLE if EXISTS Conectividad_Internet;
CREATE TABLE IF NOT EXISTS Conectividad_Internet(
  
  Provincia VARCHAR(200) , 
  Partido VARCHAR(200), 
  Localidad VARCHAR(200), 
  Poblacion int, 
  ADSL VARCHAR(50), 
  CABLEMODEM VARCHAR(50),
  DIALUP VARCHAR(20), 
  FIBRAOPTICA VARCHAR(20), 
  SATELITAL VARCHAR(20), 
  WIRELESS VARCHAR(20), 
  TELEFONIAFIJA VARCHAR(20), 
  `3G` VARCHAR(10),
  `4G` VARCHAR(10), 
  Link_Indec FLOAT, 
  Latitud VARCHAR(200), 
  Longitud VARCHAR(200));
  
  Drop TABLE if EXISTS Data_Conexiones;
  CREATE TABLE IF NOT EXISTS Data_Conexiones(
  id INT AUTO_INCREMENT PRIMARY KEY,
  Mbps_Media_bajada FLOAT, 
  Periodo Varchar(50), 
  ADSL INT, 
  Cablemodem INT,
  Fibra_óptica INT, 
  Wireless INT, 
  Otros INT, 
  Total_Conexiones INT,
  Banda_ancha_fija INT, 
  Dial_up INT, 
  Ingresos_miles_de_pesos INT, 
  Año INT,
  Trimestre INT, 
  Accesos_por_cada_100_hogares FLOAT,
  Accesos_por_cada_100_hab FLOAT
  );
  
   Drop TABLE if EXISTS Data_velocidad;
  CREATE TABLE IF NOT EXISTS Data_velocidad (
  id INT AUTO_INCREMENT PRIMARY KEY,
  Año INT, 
  Trimestre INT, 
  Provincia VARCHAR(100), 
  Banda_ancha_fija INT, 
  Dial_up INT,
  Total_Conexiones INT,
  HASTA_512_kbps INT, 
  `+ 512 Kbps - 1 Mbps` INT,
  `+ 1 Mbps - 6 Mbps` INT, 
  `+ 6 Mbps - 10 Mbps` INT, 
  `+ 10 Mbps - 20 Mbps` INT,
  `+ 20 Mbps - 30 Mbps` INT,
  `+ 30 Mbps` INT, 
  OTROS INT,
  Accesos_por_cada_100_hogares FLOAT
  );
  
   Drop TABLE if EXISTS Denuncias_Reclamos;
  CREATE TABLE IF NOT EXISTS Denuncias_Reclamos (
  id INT AUTO_INCREMENT PRIMARY KEY,
  operador VARCHAR(100),
  cantidad FLOAT
  );